//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlockStreamSatAPI.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class funcsAndDescriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal funcsAndDescriptions() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlockStreamSatAPI.Resources.funcsAndDescriptions", typeof(funcsAndDescriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вывести заказ по UUID | Only auth.
        /// </summary>
        internal static string func1_GET_order_uuid {
            get {
                return ResourceManager.GetString("func1|GET/order/uuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вывести заказ по UUID. Обязательно предоставление соответствующего авторизационного токена, чтобы доказать, что он принадлежит вам..
        /// </summary>
        internal static string func1Desc {
            get {
                return ResourceManager.GetString("func1Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вывести заказы в ожидании.
        /// </summary>
        internal static string func2_GET_orders_pending {
            get {
                return ResourceManager.GetString("func2|GET/orders/pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вывести список из 20 заказов, подлежащих оплате, отсортированный по времени создания. По вопросу разбивки на страницы, можно по желанию указать параметр before (в формате ISO 8601), с задачей предоставить в ответ 20 заказов, размещенных непосредственно перед заданным.
        /// </summary>
        internal static string func2Desc {
            get {
                return ResourceManager.GetString("func2Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вывести очередь заказов.
        /// </summary>
        internal static string func3_GET_orders_queued {
            get {
                return ResourceManager.GetString("func3|GET/orders/queued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Получить список оплаченных, но неотправленных заказов в порядке убывания ставки за байт.  Возвращаются как отложенные ордера, так и ордер, передаваемый в данный момент.  При необходимости принимает параметр, указывающий, сколько заказов в очереди нужно вернуть..
        /// </summary>
        internal static string func3Desc {
            get {
                return ResourceManager.GetString("func3Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вывести список отправленных заказов.
        /// </summary>
        internal static string func4_GET_orders_sent {
            get {
                return ResourceManager.GetString("func4|GET/orders/sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выводит список, состоящий из максимум 20 отправленных заказов в обратном хронологическом порядке. По вопросу разбивки на страницы, можно по желанию указать параметр before (в формате ISO 8601), в котором велено предоставить в ответ 20 заказов, размещенных непосредственно перед заданным временем..
        /// </summary>
        internal static string func4Desc {
            get {
                return ResourceManager.GetString("func4Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string func5 {
            get {
                return ResourceManager.GetString("func5", resourceCulture);
            }
        }
    }
}
